swagger: '2.0'
info:
  title: Documentation de l'API Bank Argent
  description: Contient tous les endpoints API disponibles dans ce codebase
  version: '1.0.0'
  termsOfService: 'http://swagger.io/terms/'
host: localhost:3001
basePath: /api/v1
schemes:
  - http
paths:
  /user/login:
    post:
      tags:
        - Module Utilisateur
      summary: Connexion
      description: API pour la connexion
      parameters:
        - in: body
          name: body
          description: Charge utile de connexion
          required: true
          schema:
            $ref: '#/definitions/Login'
      produces:
        - application/json
      responses:
        '200':
          description: Connexion réussie
          schema:
            $ref: '#/definitions/LoginResponse'
        '400':
          description: Champs invalides
        '500':
          description: Erreur interne du serveur
  /user/signup:
    post:
      tags:
        - Module Utilisateur
      summary: Inscription
      description: API pour l'inscription
      parameters:
        - in: body
          name: body
          description: Charge utile d'inscription
          required: true
          schema:
            $ref: '#/definitions/User'
      produces:
        - application/json
      responses:
        '200':
          description: Inscription réussie
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Champs invalides
        '500':
          description: Erreur interne du serveur
  /user/profile:
    post:
      security:
        - Bearer: []
      tags:
        - Module Utilisateur
      summary: API de Profil Utilisateur
      description: API pour récupérer le profil utilisateur
      responses:
        '200':
          description: Profil utilisateur récupéré avec succès
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Champs invalides
        '500':
          description: Erreur interne du serveur
    put:
      security:
        - Bearer: []
      tags:
        - Module Utilisateur
      summary: API de Profil Utilisateur
      description: API pour mettre à jour le profil utilisateur
      parameters:
        - in: body
          name: body
          description: Mettre à jour les attributs du profil utilisateur
          required: true
          schema:
            $ref: '#/definitions/UserProfile'
      produces:
        - application/json
      responses:
        '200':
          description: Profil utilisateur mis à jour avec succès
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Champs invalides
        '500':
          description: Erreur interne du serveur
  /transactions:
    get:
      tags:
        - Module Transactions
      summary: Récupérer toutes les transactions
      description: Récupérer toutes les transactions pour le mois en cours, groupées par compte
      parameters:
        - name: accountId
          in: query
          description: Filtrer les transactions par ID de compte
          required: false
          type: string
      responses:
        '200':
          description: Opération réussie
          schema:
            type: array
            items:
              $ref: '#/definitions/Transaction'
        '400':
          description: Paramètre de requête invalide
        '500':
          description: Erreur du serveur
  /transactions/{transactionId}:
    get:
      tags:
        - Module Transactions
      summary: Récupérer les détails d'une transaction
      description: Récupérer les informations détaillées pour une transaction spécifique
      parameters:
        - name: transactionId
          in: path
          description: L'ID de la transaction
          required: true
          type: string
      responses:
        '200':
          description: Détails de la transaction récupérés avec succès
          schema:
            $ref: '#/definitions/TransactionDetails'
        '404':
          description: Transaction non trouvée
        '500':
          description: Erreur du serveur
   
      tags:
        - Module Transactions
      summary: Mettre à jour une transaction
      description: Mettre à jour les informations d'une transaction spécifique
      parameters:
        - name: transactionId
          in: path
          description: L'ID de la transaction
          required: true
          type: string
        - in: body
          name: body
          description: Les nouvelles données de la transaction
          required: true
          schema:
            $ref: '#/definitions/TransactionUpdate'
      responses:
        '200':
          description: Transaction mise à jour avec succès
        '400':
          description: Données d'entrée invalides
        '404':
          description: Transaction non trouvée
        '500':
          description: Erreur du serveur
  /transactions/{transactionId}/note:
    post:
      tags:
        - Module Transactions
      summary: Ajouter une note à une transaction
      description: Ajouter une note à une transaction spécifique
      parameters:
        - name: transactionId
          in: path
          description: L'ID de la transaction
          required: true
          type: string
        - in: body
          name: body
          description: Les données de la note
          required: true
          schema:
            $ref: '#/definitions/Note'
      responses:
        '201':
          description: Note ajoutée avec succès
        '400':
          description: Données d'entrée invalides
        '404':
          description: Transaction non trouvée
        '500':
          description: Erreur du serveur
  /transactions/{transactionId}/category:
    put:
      tags:
        - Module Transactions
      summary: Modifier la catégorie d'une transaction
      description: Mettre à jour la catégorie d'une transaction spécifique
      parameters:
        - name: transactionId
          in: path
          description: L'ID de la transaction
          required: true
          type: string
        - in: body
          name: body
          description: Les nouvelles données de la catégorie
          required: true
          schema:
            $ref: '#/definitions/Category'
      responses:
        '200':
          description: Catégorie mise à jour avec succès
        '400':
          description: Données d'entrée invalides
        '404':
          description: Transaction non trouvée
        '500':
          description: Erreur du serveur
securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
definitions:
  User:
    properties:
      email:
        type: string
        description: email de l'utilisateur
      password:
        type: string
        description: mot de passe de l'utilisateur
      firstName:
        type: string
        description: prénom de l'utilisateur
      lastName:
        type: string
        description: nom de famille de l'utilisateur
      userName:
        type: string
        description: nom public de l'utilisateur
  Login:
    properties:
      email:
        type: string
        description: email de l'utilisateur
      password:
        type: string
        description: mot de passe de l'utilisateur
  ApiResponse:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: object
        properties:
          id:
            type: string
          email:
            type: string
  LoginResponse:
    type: object
    properties:
      token:
        type: string
  UserProfile:
    type: object
    properties:
      userName:
        type: string
  Transaction:
    type: object
    properties:
      date:
        type: string
        format: date
      description:
        type: string
      amount:
        type: number
      balance:
        type: number
      transactionType:
        type: string
      category:
        type: string
      note:
        type: string
  TransactionDetails:
    type: object
    properties:
      date:
        type: string
        format: date
      description:
        type: string
      amount:
        type: number
      balance:
        type: number
      transactionType:
        type: string
      category:
        type: string
      note:
        type: string
  Note:
    type: object
    properties:
      note:
        type: string
  Category:
    type: object
    properties:
      category:
        type: string
